[package]
name = "rsi_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rdkafka = { version = "0.38.0", features = ["tokio"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
futures-util = "0.3.31"
warp = "0.3"

